on: [push]
jobs:
  tests:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        lisp:
          - sbcl-bin
          - ecl
          - ccl-bin
          - abcl-bin
          # - clasp-bin
          # - cmu-bin
          # - clisp-head
        # Not all combinations works, so we disable some
        exclude:
          # ccl-bin/system does not exist.stop.
          - os: macos-latest
            lisp: ccl-bin
          # ecl/system does not exist.stop.
          - os: windows-latest
            lisp: ecl
          # ccl-bin/system does not exist.stop.
          - os: windows-latest
            lisp: ccl-bin
          # abcl-bin/system does not exist.stop.
          - os: windows-latest
            lisp: abcl-bin
      fail-fast: false
    runs-on: ${{ matrix.os }}
    env:
      LISP: ${{ matrix.lisp }}
    steps:
      - uses: actions/checkout@v4
      - uses: 40ants/setup-lisp@v4
        with:
          asdf-system: sijo-doctest
          qlfile-template: |
            dist ultralisp http://dist.ultralisp.org
      - uses: 40ants/run-tests@v2
        with:
          asdf-system: sijo-doctest
